controllers/admin_article.py
#! /usr/bin/python
# -*- coding:utf-8 -*-
from flask import Blueprint
from flask import Flask, request, render_template, redirect, url_for, abort, flash, session, g

from connexion_db import get_db

admin_article = Blueprint('admin_article', __name__,
                        template_folder='templates')

@admin_article.route('/article/show')
def show_article():
    mycursor = get_db().cursor()
    sql = "SELECT * FROM article"
    mycursor.execute(sql)
    articles = mycursor.fetchall()
    # print(articles)
    return render_template('article/show_article.html', articles=articles)

@admin_article.route('/article/add', methods=['GET'])
def add_article():
    mycursor = get_db().cursor()
    sql = "SELECT * FROM type_article"
    mycursor.execute(sql)
    types_articles = mycursor.fetchall()
    return render_template('article/add_article.html', types_articles=types_articles)

@admin_article.route('/article/add', methods=['POST'])
def valid_add_article():
    nom = request.form.get('nom', '')
    type_article_id = request.form.get('type_article_id', '')
   # type_article_id = int(type_article_id)
    prix = request.form.get('prix', '')
    stock = request.form.get('stock', '')
    description = request.form.get('description', '')
    image = request.form.get('image', '')
    tuple_insert = (nom,type_article_id,prix,stock,description,image)
    sql = "INSERT INTO article(nom,type_article_id,prix,stock,description,image) VALUES (%s,%s,%s,%s,%s,%s);"
    mycursor = get_db().cursor()
    mycursor.execute(sql, tuple_insert)
    get_db().commit()
    print(u'article ajouté , nom: ', nom, ' - type_article:', type_article_id, ' - prix:', prix, ' - stock:', stock, ' - description:', description, ' - image:', image)
    message = u'article ajouté , nom:'+nom + '- type_article:' + type_article_id + ' - prix:' + prix + ' - stock:'+  stock + ' - description:' + description + ' - image:' + image
    flash(message)
    return redirect(url_for('admin_article.show_article'))

@admin_article.route('/article/delete', methods=['POST'])
def delete_article():
    # id = request.args.get('id', '')
    id = request.form.get('id', '')
    tuple_delete = (id,)
    sql = "DELETE FROM article WHERE id = %s;"
    mycursor = get_db().cursor()
    mycursor.execute(sql, tuple_delete)
    get_db().commit()
    print("un article supprimé, id :", id)
    flash(u'un article supprimé, id : ' + id)
    return redirect(url_for('admin_article.show_article'))

@admin_article.route('/article/edit/<int:id>', methods=['GET'])
def edit_article(id):
    mycursor = get_db().cursor()
    sql = "SELECT * FROM article where id=%s"
    mycursor.execute(sql, (id,))
    article = mycursor.fetchone()
    sql = "SELECT * FROM type_article"
    mycursor.execute(sql)
    types_articles = mycursor.fetchall()
    return render_template('article/edit_article.html', article=article, types_articles=types_articles)

@admin_article.route('/article/edit', methods=['POST'])
def valid_edit_article():
    nom = request.form['nom']
    id = request.form.get('id', '')
    type_article_id = request.form.get('type_article_id', '')
    #type_article_id = int(type_article_id)
    prix = request.form.get('prix', '')
    stock = request.form.get('stock', '')
    description = request.form.get('description', '')
    image = request.form.get('image', '')
    tuple_update = (nom,type_article_id,prix,stock,description,image,id)
    sql = "UPDATE article SET nom=%s, type_article_id=%s,prix=%s,stock=%s,description=%s,image=%s WHERE id = %s;"
    mycursor = get_db().cursor()
    mycursor.execute(sql, tuple_update)
    get_db().commit()
    print(u'article modifié , nom : ', nom, ' - type_article:', type_article_id, ' - prix:', prix, ' - stock:', stock, ' - description:', description, ' - image:', image)
    message = u'article modifié , nom:'+nom + '- type_article:' + type_article_id + ' - prix:' + prix + ' - stock:'+  stock + ' - description:' + description + ' - image:' + image
    flash(message)
    return redirect(url_for('admin_article.show_article'))

controllers/admin_type_article.py
#! /usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import Flask, request, render_template, redirect, url_for, abort, flash, session, g

from connexion_db import get_db

admin_type_article = Blueprint('admin_type_article', __name__,
                        template_folder='templates')

@admin_type_article.route('/type-article/show')
def show_type_article():
    mycursor = get_db().cursor()
    sql = "SELECT * FROM type_article"
    mycursor.execute(sql)
    types_articles = mycursor.fetchall()
    return render_template('type_article/show_type_article.html', types_articles=types_articles)

@admin_type_article.route('/type-article/add', methods=['GET'])
def add_type_article():
    return render_template('type_article/add_type_article.html')

@admin_type_article.route('/type-article/add', methods=['POST'])
def valid_add_type_article():
    libelle = request.form.get('libelle', '')
    tuple_insert = (libelle,)
    mycursor = get_db().cursor()
    sql = "INSERT INTO type_article(libelle) VALUES (%s);"
    mycursor.execute(sql, tuple_insert)
    get_db().commit()
    message = u'type ajouté , libellé :'+libelle
    flash(message)
    return redirect(url_for('admin_type_article.show_type_article'))

@admin_type_article.route('/type-article/delete', methods=['POST'])
def delete_type_article():
    #id_type_article = request.args.get('id', '')
    id_type_article = request.form.get('id', '')
    mycursor = get_db().cursor()
    tuple_delete = (id_type_article,)
    sql = "DELETE FROM type_article WHERE id = %s;"
    mycursor.execute(sql, tuple_delete)
    get_db().commit()
    flash(u'un type d\'article supprimé, id : ' + id_type_article)
    return redirect(url_for('admin_type_article.show_type_article'))

@admin_type_article.route('/type-article/edit/<int:id>', methods=['GET'])
def edit_type_article(id):
    mycursor = get_db().cursor()
    sql = "SELECT id,libelle FROM type_article where id=%s"
    mycursor.execute(sql, (id,))
    type_article = mycursor.fetchone()
    return render_template('type_article/edit_type_article.html', type_article=type_article)

@admin_type_article.route('/type-article/edit', methods=['POST'])
def valid_edit_type_article():
    libelle = request.form['libelle']
    id_type_article = request.form.get('id', '')
    tuple_update = (libelle, id_type_article)
    mycursor = get_db().cursor()
    sql = "UPDATE type_article SET libelle =%s WHERE id = %s;"
    mycursor.execute(sql, tuple_update)
    get_db().commit()
    flash(u'type article modifié, id: ' + id_type_article + " libelle : " + libelle)
    return redirect(url_for('admin_type_article.show_type_article'))

templates/_nav.html
<nav class="menu">
    <a href="/article/show"> article </a>  -
    <a href="/type-article/show"> type d'article </a>  -
    {#<a href="{{ url_for('show_type_article') }}"> type d'article </a>#}
</nav>
<hr>

templates/article/add_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>ajouter un article</title>
{% endblock %}

{% block body %}
  <h2>ajout d'un article</h2>
  {% if error %}
    <p class=error><strong>Error:</strong> {{ error }}
  {% endif %}
  <form method="post" action="/article/add" {#action="{{ url_for('valid_add_article') }}#}>
    <fieldset>
        <legend> Créer un article</legend>
        <label for="nom">nom</label><br>
        <input id="nom" type="text" name="nom" size="18" value="" placeholder="Saisir le nom de l'article"><br>
       <!-- <label for="type_article_id">id type de l'article</label><br>
        <input id="type_article_id" type="text" name="type_article_id" size="18" value="" placeholder="Saisir l'id du type de l'article"><br>
       -->
        <br>
        <label for="type_article_id">type de l'article</label>
        <select name="type_article_id" required>
            <option value="">Sélectionner un article</option>
            {% for type in types_articles %}
            <option value="{{ type.id }}"> {{ type.libelle }} </option>
            {% endfor %}
        </select><br>


        <label for="prix">prix de l'article</label><br>
        <input id="prix" type="number" step="0.01"  required name="prix" size="18" value="" placeholder="Saisir le prix de l'article"><br>
        <label for="stock">stock</label><br>
        <input id="stock" type="number"  required name="stock" size="18" value="" placeholder="Saisir le stock"><br>
        <label for="description">description</label><br>
        <input id="description" type="text" name="description" size="18" value="" placeholder="Saisir la description"><br>
        <label for="image">image</label><br>
        <input id="image" type="text" name="image" size="18" value="" placeholder="Saisir le nom de l'image de l'article"><br>
{#        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
        <input type="submit" value="Creer" name="Valider" >
    </fieldset>
  </form>
{% endblock %}

templates/article/edit_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>modifier un article</title>
{% endblock %}

{% block body %}
  <h2>modifier d'un article</h2>
  {% if error %}
    <p class=error><strong>Error:</strong> {{ error }}
  {% endif %}
  <form method="post" action="/article/edit" {#action="{{ url_for('valid_edit_article') }}#}>
    <fieldset>
        <legend> Modifier un article</legend>
        <input type="hidden" name="id" size="18" value="{{ article.id }}" id="id">

        <label for="nom">nom</label><br>
        <input id="nom" type="text" name="nom" size="18" value="{{ article.nom }}" placeholder="Saisir le nom de l'article"><br>
        <!-- <label for="type_article_id">id type de l'article</label><br>
        <input id="type_article_id" type="text" name="type_article_id" size="18" value="{{ article.type_article_id }}" placeholder="Saisir l'id du type de l'article"><br>
        --><br>
        <label for="type_article_id">type de l'article</label>
        <select name="type_article_id" required>
            {% for type in types_articles %}
            <option value="{{ type.id }}"
                    {% if article.type_article_id is defined and type.id ==  article.type_article_id %}selected{% endif %}
            > {{ type.libelle }} </option>
            {% endfor %}
        </select><br>

        <label for="prix">prix de l'article</label><br>
        <input id="prix" type="number" step="0.01" required name="prix" size="18" value="{{ article.prix }}" placeholder="Saisir le prix de l'article"><br>
        <label for="stock">stock</label><br>
        <input id="stock" type="number"  required name="stock" size="18" value="{{ article.stock }}" placeholder="Saisir le stock"><br>
        <label for="description">description</label><br>
        <input id="description" type="text" name="description" size="18" value="{{ article.description }}" placeholder="Saisir la description"><br>
        <label for="image">image</label><br>
        <input id="image" type="text" name="image" size="18" value="{{ article.image }}" placeholder="Saisir le nom de l'image de l'article"><br>

{#        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
        <input type="submit" value="Modifier" name="Valider" >
    </fieldset>
  </form>
{% endblock %}

templates/article/show_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>afficher les articles</title>
{% endblock %}

{% block body %}
<h3>article</h3>
<a href="/article/add">ajouter un article</a>
<br><br>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>id</th><th>nom</th><th>id type article</th><th>prix</th><th>stock</th>
            <th>description</th><th>image</th><th>operation</th>
        </tr>
    </thead>
    <tbody>
    {% if articles | length >= 1 %}
        {% for ligne in articles %}
           <tr>
                  <td>{{ ligne.id }}</td>
                  <td>{{ ligne.nom }}</td>
                  <td>{{ ligne.type_article_id }}</td>
                  <td>{{ ligne.prix }}  {#{  "{:,.2f} €".format(ligne.prix) }#}</td>
                  <td>{{ ligne.stock }}</td>
                  <td>{{ ligne.description }}</td>
                  <td>{{ ligne.date_create }} {#{ ligne.date_create.strftime('%d-%m-%Y') }#} </td>
                  <td>{{ ligne.image }}
                        {%  if ligne.image is not none %}
                            <img style="width:40px;height:40px"  src="{{ url_for('static', filename = 'images/' + ligne['image']) }}"  alt="image  de {{ ligne.nom }}" >
                        {% else %}
                            <img style="width:40px;height:40px"   src="{{ url_for('static', filename='images/no_photo.jpeg')}}"  alt="pas d image" >
                        {% endif %}
                  </td>
                  <td>
                  {#<a href="/article/delete?id={{ ligne.id }}" onclick="return confirm('Are you sure?')" >supprimer</a>#}
                        <form action="/article/delete" method="POST" style="display:inline">
{#                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
                            <input type="hidden" name="id" value="{{ ligne.id }}">
                            {#<input type="hidden" name="_method" value="DELETE">#}
                            <button type="submit" class="btn btn-warning">Supprimer</button>
                        </form>
                  </td>
                  <td>
                      <a href="/article/edit/{{ ligne.id }}">editer</a>
                  </td>
           </tr>
        {% endfor %}
    {% else %}
            <tr>
                  <td>
                      pas d'article
                  </td>
           </tr>
    {% endif %}
    </tbody>
</table>
{% endblock %}

templates/csrf_error.html
erreur CSRF

<br>
{{ reason }}

templates/layout.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block title %}
        <title>layout</title>
    {% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" >
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ url_for('static', filename='mes_styles.css') }}" >
        {#<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}" >#}
    {% endblock %}
</head>
<body>
{% include('_nav.html') %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<ul class="flashes">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

{% block body %}
    <h2 style="color:blue">layout.html.twig</h2>
{% endblock %}
{% block javascripts %}
    {#<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>#}
{% endblock %}
</body>
</html>

templates/type_article/add_type_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>ajouter un type d'article</title>
{% endblock %}

{% block body %}
  <h2>ajout d'un type d'article</h2>
  {% if error %}
    <p class=error><strong>Error:</strong> {{ error }}
  {% endif %}
  <form method="post" action="/type-article/add" {#action="{{ url_for('valid_add_type_article') }}#}>
    <fieldset>
        <legend> Créer un type d'article</legend>
        <label for="libelle">libelle</label><br>
        <input id="libelle" type="text" name="libelle" size="18" value="" placeholder="Saisir le libelle du type de l'article"><br>
        <input type="submit" value="Creer" name="Valider" >
{##}
{#{{ form.hidden_tag() }}#}
{#        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
    </fieldset>
  </form>
{% endblock %}

templates/type_article/edit_type_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>modifier un type d'article</title>
{% endblock %}

{% block body %}
  <h2>modifier un type d'article</h2>
  {% if error %}
    <p class=error><strong>Error:</strong> {{ error }}
  {% endif %}
  <form method="post" action="{{ url_for('admin_type_article.valid_edit_type_article') }}">
    <fieldset>
        <legend> Modifier un type d'article</legend>
        <input type="hidden" name="id" size="18" value="{{ type_article.id }}" id="id">
        <label for="libelle">libelle</label><br>
        <input type="text" name="libelle" size="18" value="{{ type_article.libelle }}" id="libelle"><br>
        <input type="submit" value="Modifier" name="Modifier" >
{#        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
    </fieldset>
  </form>
{% endblock %}

templates/type_article/show_type_article.html
{% extends 'layout.html' %}

{% block title %}
    <title>afficher les types d'article</title>
{% endblock %}

{% block body %}
<h3>Types d'article</h3>
<a href="/type-article/add">ajouter un type d'article</a>
<br><br>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>id</th><th>designation</th><th>opération</th>
        </tr>
    </thead>
    <tbody>
    {% if types_articles | length >= 1 %}
        {% for ligne in types_articles %}
           <tr>
                  <td>{{ ligne.id }}</td>
                  <td>{{ ligne.libelle }}</td>
                  <td>
                      <a href="/type-article/edit/{{ ligne.id }}">editer</a>&nbsp;
                     {# <a href="/type-article/delete?id={{ ligne.id }}" onclick="return confirm('Are you sure?')" >supprimer</a>#}

                  {#<a href="/article/delete?id={{ ligne.id }}" onclick="return confirm('Are you sure?')" >supprimer</a>#}
                        <form action="/type-article/delete" method="POST" style="display:inline">
{#                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
                            <input type="hidden" name="id" value="{{ ligne.id }}">
                            {#<input type="hidden" name="_method" value="DELETE">#}
                            <button type="submit" class="btn btn-warning">Supprimer</button>
                        </form>
                  </td>
           </tr>
        {% endfor %}
    {% else %}
            <tr>
                  <td>
                      pas de type d'article
                  </td>
           </tr>
    {% endif %}
    </tbody>
</table>
{% endblock %}